# Generated by Django 3.2 on 2022-02-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRestaurant', '0003_orderplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplace',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
